# Generated by Django 3.2.8 on 2021-11-14 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0002_auto_20211114_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followupnotes',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.sales'),
        ),
    ]
