# Generated by Django 3.2.8 on 2021-11-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20211114_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='followupdate',
            field=models.DateField(auto_now=True, verbose_name='vote date'),
        ),
    ]
