# Generated by Django 3.2.8 on 2021-11-15 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_sales_followupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='followupdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
