# Generated by Django 3.2.8 on 2021-11-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_followupnotes_followupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
