# Generated by Django 3.2.8 on 2021-11-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20211116_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='extend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
